### ISSUE TITLE
ubuntu 23.10 night light

### ISSUE THREAD

**Issue by dooraim** [tobhe/ubuntu-asahi#92] opened 2024-02-11 16:25 UTC
I'm using the following version of Ubuntu and Asahi Linux Kernel,

```bash
ubuntu@macbookm1pro:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
ubuntu@macbookm1pro:~$ uname -a
Linux macbookm1pro 6.6.0-1003-apple-arm #3-Ubuntu SMP PREEMPT_DYNAMIC Wed Dec 27 01:40:02 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
ubuntu@macbookm1pro:~$ 
```

I can not using Night Light, also if I have GPU driver installed. 

There is any solution about this issue? Or is there a 3rd parts software to install that make the same functions?

**Comment by eslerm** [comment] 2024-02-14 07:30
This is likely a duplicate of https://github.com/UbuntuAsahi/ubuntu-asahi/issues/53

For these issues I'll do some testing over the weekend.

[wlsunset](https://sr.ht/~kennylevinsen/wlsunset/) might be a solution.

**Comment by dooraim** [comment] 2024-02-16 08:01
@eslerm tnx, I will try your suggestions

**Comment by dooraim** [comment] 2024-02-16 18:59
@eslerm I have the following error

```
╰─❯ wlsunset -l 39.9 -L 116.3                                              78%
registry: adding output 4
skipping setup of output 4: gamma_control_manager missing
compositor doesn't support wlr-gamma-control-unstable-v1
```

**Comment by eslerm** [comment] 2024-02-18 07:45
Thanks for testing @dooraim :pray: 

I posted some followup in https://github.com/UbuntuAsahi/ubuntu-asahi/issues/53#issuecomment-1950992211

I'm going to close this issue as a duplicate to keep the conversation in the original thread.

**Closed as completed by eslerm** 2024-02-18 07:45 UTC
