### ISSUE TITLE
Problem with go module

### ISSUE THREAD

**Issue by akifakif32** [tobhe/ubuntu-asahi#54] opened 2023-08-30 10:20 UTC
![20230830_131859](https://github.com/UbuntuAsahi/ubuntu-asahi/assets/120502131/5373f112-c236-44d1-a638-ab7d852a5fcf)
In all versions of Ubuntu I encountered same issue. Ubuntu cannot execute go module

**Comment by tobhe** [comment] 2023-08-30 11:03
"Exec format error" and linux-x86 sounds like you are trying to run a non-arm64 binary.

**Comment by akifakif32** [comment] 2023-08-30 11:05
Well because I am trying to compile a twrp and that's the only way to do so, this file worked on my old Asus computer with Ubuntu 20.04

**Comment by tobhe** [comment] 2023-08-30 11:14
I have no doubt that it works on an old x86 computer, but it won't work on an arm64 CPU. Your best bet is asking the twrp community if they support building on arm64. This is not an Ubuntu issue.

**Comment by akifakif32** [comment] 2023-08-30 11:16
Actually the weird thing is that according to TWRP building community arm64 is advices to build with same tools and my old Asus was 64 bit too

**Comment by clementperon** [comment] 2023-09-02 10:18
You're mixing two architecture: x86-64/amd64 and aarch64/arm64. Your old Asus was an AMD64 not an ARM64.

So the issue is not comming from Ubuntu Asahi but from TWRP that doesn't support building with ARM64 machine as a host.

Better to open an issue on TWRP side and close this one

**Comment by akifakif32** [comment] 2023-09-05 16:45
ooh I see so I decided to buy a laptop with amd64 processor thank you!

**Comment by clementperon** [comment] 2023-10-08 20:08
@akifakif32 can you close this issue then?

**Closed as completed** 2023-10-08 20:36 UTC
