### ISSUE TITLE
macbook air 15 inch not support

### ISSUE THREAD

**Issue by eret9616** [tobhe/ubuntu-asahi#48] opened 2023-07-18 16:32 UTC

**Comment by eslerm** [comment] 2023-07-18 17:34
Macbook Air 15" M2s will be supported after Asahi Linux adds support in their stable release. Closing this issue as a duplicate of https://github.com/UbuntuAsahi/ubuntu-asahi/issues/29

**Closed as completed by eslerm** 2023-07-18 17:34 UTC
