### ISSUE TITLE
I CAN not install this no matter what!!  

### ISSUE THREAD

**Issue by astroskyoffical** [tobhe/ubuntu-asahi#102] opened 2024-04-04 02:22 UTC
[log.txt](https://github.com/UbuntuAsahi/ubuntu-asahi/files/14860512/log.txt)

log attached, i have enough freespace and no matter what i do i cant proceed to install this ! its driving me nuts and id appreciate a more keen eye to help me out.  please someone?   im just a bit frustrated.   i tried asahi linux mainline and i didnt enjoy it mainly due to its flatpaks and other none user friendly ways of doing things.   i much prefer ubuntu for the most part so this would be great to get working on my system

**Comment by eslerm** [comment] 2024-04-04 03:09
@tobhe [mentioned that the file server might be down today](https://oftc.irclog.whitequark.org/ubuntu-asahi/2024-04-03) and your log.txt suggest that downloading the image file failed.

Hopefully it will just work after tobhe gives the all clear tomorrow :)

**Comment by tobhe** [comment] 2024-04-04 10:53
Indeed, looks like something went wrong when moving some things to a new host. Should be fixed now, thanks for letting us know @astroskyoffical !

**Comment by astroskyoffical** [comment] 2024-04-04 18:38
unfortunately even after reinstalling......its the same issue....      I also reinstalled my entire system just In case a configuration was the problem  @tobhe  @eslerm 
















Last login: Thu Apr  4 05:25:25 on console
astro@Austins-MacBook-Air ~ % curl -sL https://ubuntuasahi.org/install | sh
Bootstrapping installer:
  Checking version...
  Version: v0.7.1
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
Password:

Welcome to the Asahi Linux installer!

This installer will guide you through the process of setting up
Asahi Linux on your Mac.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.


Collecting system information...
  Product name: MacBook Air (M1, 2020)
  SoC: Apple M1
  Device class: j313ap
  Product type: MacBookAir10,1
  Board ID: 0x26
  Chip ID: 0x8103
  System firmware: iBoot-10151.41.12
  Boot UUID: 7DAD646C-13CF-4316-A62B-9A5EB7667215
  Boot VGID: 7DAD646C-13CF-4316-A62B-9A5EB7667215
  Default boot VGID: 7DAD646C-13CF-4316-A62B-9A5EB7667215
  Boot mode: macOS
  OS version: 14.1 (23B74)
  OS restore version: 23.2.74.0.0,0
  Main firmware version: 14.1 (23B74)
  No Fallback System Firmware / rOS
  SFR version: 23.2.74.0.0,0
  SystemRecovery version: 23.2.74.0.0,0 (14.1 23B74)
  Login user: astro

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (245.11 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v14.1 [disk3s1s1, 7DAD646C-13CF-4316-A62B-9A5EB7667215]
  2: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v14.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1s1) for machine authentication.

Choose what to do:
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (r): r


We're going to resize this partition:
  APFS [Macintosh HD] (245.11 GB, 6 volumes)
  Total size: 245.11 GB
  Free space: 225.64 GB
  Available space: 187.64 GB
  Overhead: 0 B
  Minimum new size: 57.47 GB (23.45%)

Enter the new size for your existing partition:
  You can enter a size such as '1GB', a fraction such as '50%',
  or the word 'min' for the smallest allowable size.

  Examples:
  30%  - 30% to macOS, 70% to the new OS
  80GB - 80GB to macOS, the rest to your new OS
  min  - Shrink macOS as much as (safely) possible

» New size (50%): 40%

Resizing will free up 147.06 GB of space.

Note: your system may appear to freeze during the resize.
This is normal, just wait until the process completes.
» Continue? (y/N): y

Started APFS operation
Aligning shrink delta to 147,064,291,328 bytes and targeting a new container size of 98,042,904,576 bytes
Determined the minimum size for the APFS Container to be 20,199,768,064 bytes
Resizing APFS Container designated by APFS Container Reference disk3
The specific APFS Physical Store being resized is disk0s2
Verifying storage system
Using live mode
Performing fsck_apfs -n -x -l /dev/disk0s2
Checking the container superblock
Checking the checkpoint with transaction ID 2523
Checking the space manager
Checking the space manager free queue trees
Checking the object map
Checking the encryption key structures
Checking volume /dev/rdisk3s1
Checking the APFS volume superblock
The volume Macintosh HD was formatted by newfs_apfs (1677.41.3.101.1) and last modified by apfs_kext (2235.41.1)
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking snapshot 1 of 1 (com.apple.os.update-0E668A68AC744DECF94EFD6DB452954A3976F45D11161E39EB75ED87C5104FF8)
Checking the fsroot tree
Checking the file extent tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s1 with UUID 84217A7F-7279-48B6-A2CE-53EAB0CCF96B appears to be OK
Checking volume /dev/rdisk3s2
Checking the APFS volume superblock
The volume Preboot was formatted by newfs_apfs (2235.41.1) and last modified by apfs_kext (2235.41.1)
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s2 with UUID 0A6FBD17-E44E-4632-984A-48D3031E0CC6 appears to be OK
Checking volume /dev/rdisk3s3
Checking the APFS volume superblock
The volume Recovery was formatted by newfs_apfs (2235.41.1) and last modified by apfs_kext (2235.41.1)
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s3 with UUID 24BDB348-E701-4E18-BB49-B76D4AB7F817 appears to be OK
Checking volume /dev/rdisk3s4
Checking the APFS volume superblock
The volume Update was formatted by newfs_apfs (2235.41.1) and last modified by apfs_kext (2235.41.1)
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s4 with UUID D06C6C8A-7A42-4E3F-8F1D-BC144B1EB9F4 appears to be OK
Checking volume /dev/rdisk3s5
Checking the APFS volume superblock
The volume Data was formatted by newfs_apfs (2235.41.1) and last modified by apfs_kext (2235.41.1)
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the document ID tree
Checking the fsroot tree
Checking the extent ref tree
Checking the file key rolling tree
Verifying volume object map space
The volume /dev/rdisk3s5 with UUID 7DAD646C-13CF-4316-A62B-9A5EB7667215 appears to be OK
Checking volume /dev/rdisk3s6
Checking the APFS volume superblock
The volume VM was formatted by apfs_boot_util (2235.41.1) and last modified by 
Checking the object map
Checking the snapshot metadata tree
Checking the snapshot metadata
Checking the fsroot tree
Checking the extent ref tree
Verifying volume object map space
The volume /dev/rdisk3s6 with UUID F2F8C4E8-8F5B-4D42-B34F-FB78B635706E appears to be OK
Verifying allocated space
The container /dev/disk0s2 appears to be OK
Storage system check exit code is 0
Shrinking APFS Physical Store disk0s2 from 245,107,195,904 to 98,042,904,576 bytes
Shrinking APFS data structures
Shrinking partition
Modifying partition map
Finished APFS operation

Resize complete. Press enter to continue.


Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (98.04 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v14.1 [disk3s1s1, 7DAD646C-13CF-4316-A62B-9A5EB7667215]
  2: (free space: 147.06 GB)
  3: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v14.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1s1) for machine authentication.

Choose what to do:
  f: Install an OS into free space
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (f): f

Choose an OS to install:
  1: Ubuntu Desktop 23.10
» OS: 1

Downloading OS package info...
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1058, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 866, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1021, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 292, in action_install_into_free
    self.osins.load_package()
  File "/private/tmp/asahi-install/osinstall.py", line 47, in load_package
    self.ucache = urlcache.URLCache(package)
  File "/private/tmp/asahi-install/urlcache.py", line 26, in __init__
    self.size = self.get_size()
  File "/private/tmp/asahi-install/urlcache.py", line 75, in get_size
    return int(res.getheader("Content-length"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
astro@Austins-MacBook-Air ~ % curl -sL https://ubuntuasahi.org/install | sh
Bootstrapping installer:
  Checking version...
  Version: v0.7.1
  Downloading...
  Extracting...
  Initializing...

The installer needs to run as root.
Please enter your sudo password if prompted.
Password:

Welcome to the Asahi Linux installer!

This installer will guide you through the process of setting up
Asahi Linux on your Mac.

Please make sure you are familiar with our documentation at:
  https://alx.sh/w

Press enter to continue.


Collecting system information...
  Product name: MacBook Air (M1, 2020)
  SoC: Apple M1
  Device class: j313ap
  Product type: MacBookAir10,1
  Board ID: 0x26
  Chip ID: 0x8103
  System firmware: iBoot-10151.41.12
  Boot UUID: 7DAD646C-13CF-4316-A62B-9A5EB7667215
  Boot VGID: 7DAD646C-13CF-4316-A62B-9A5EB7667215
  Default boot VGID: 7DAD646C-13CF-4316-A62B-9A5EB7667215
  Boot mode: macOS
  OS version: 14.1 (23B74)
  OS restore version: 23.2.74.0.0,0
  Main firmware version: 14.1 (23B74)
  No Fallback System Firmware / rOS
  SFR version: 23.2.74.0.0,0
  SystemRecovery version: 23.2.74.0.0,0 (14.1 23B74)
  Login user: astro

Collecting partition information...
  System disk: disk0

Collecting OS information...

Partitions in system disk (disk0):
  1: APFS [Macintosh HD] (98.04 GB, 6 volumes)
    OS: [B*] [Macintosh HD] macOS v14.1 [disk3s1s1, 7DAD646C-13CF-4316-A62B-9A5EB7667215]
  2: (free space: 147.06 GB)
  3: APFS (System Recovery) (5.37 GB, 2 volumes)
    OS: [  ] recoveryOS v14.1 [Primary recoveryOS]

  [B ] = Booted OS, [R ] = Booted recovery, [? ] = Unknown
  [ *] = Default boot volume

Using OS 'Macintosh HD' (disk3s1s1) for machine authentication.

Choose what to do:
  f: Install an OS into free space
  r: Resize an existing partition to make space for a new OS
  q: Quit without doing anything
» Action (f): f

Choose an OS to install:
  1: Ubuntu Desktop 23.10
» OS: 1

Downloading OS package info...
root        : ERROR    Exception caught
Traceback (most recent call last):
  File "/private/tmp/asahi-install/main.py", line 1058, in <module>
    InstallerMain(installer_version).main()
  File "/private/tmp/asahi-install/main.py", line 866, in main
    while self.main_loop():
  File "/private/tmp/asahi-install/main.py", line 1021, in main_loop
    return self.action_install_into_free(parts_free)
  File "/private/tmp/asahi-install/main.py", line 292, in action_install_into_free
    self.osins.load_package()
  File "/private/tmp/asahi-install/osinstall.py", line 47, in load_package
    self.ucache = urlcache.URLCache(package)
  File "/private/tmp/asahi-install/urlcache.py", line 26, in __init__
    self.size = self.get_size()
  File "/private/tmp/asahi-install/urlcache.py", line 75, in get_size
    return int(res.getheader("Content-length"))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
If you need to file a bug report, please attach the log file:
  /private/tmp/asahi-install/installer.log
astro@Austins-MacBook-Air ~ %

**Comment by tobhe** [comment] 2024-04-04 23:42
Probably just your DNS cache being outdated, you might have to flush it or wait a bit longer. I verified it works here.

**Comment by eslerm** [comment] 2024-04-17 19:19
@astroskyoffical any luck?

**Comment by tobhe** [comment] 2024-04-29 21:13
Closing this one since we believe the issue is fixed. Thanks!

**Closed as completed by tobhe** 2024-04-29 21:13 UTC
